# ==========================================
# Trading Bot V4 - CONFIG
# ==========================================

START_BALANCE = 100.0

SYMBOLS = [
    "BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT",
    "DOGEUSDT","ADAUSDT","LINKUSDT","AVAXUSDT","DOTUSDT",
    "TRXUSDT","TONUSDT","LTCUSDT","BCHUSDT","ATOMUSDT",
    "UNIUSDT","AAVEUSDT","NEARUSDT","APTUSDT","ARBUSDT",
    "OPUSDT","INJUSDT","SUIUSDT","SEIUSDT","HBARUSDT",
    "FILUSDT","ETCUSDT","ALGOUSDT","VETUSDT","ICPUSDT",
]

LOWER_TIMEFRAME = "15m"
HIGHER_TIMEFRAME = "1h"
CANDLE_LIMIT = 300
SCAN_SECONDS = 30

EMA_FAST = 20
EMA_SLOW = 50
EMA_TREND = 200

RSI_PERIOD = 14
RSI_MIN = 52
RSI_MAX = 68

ATR_PERIOD = 14
MIN_ATR_PERCENT = 0.003
MAX_ATR_PERCENT = 0.030

VOLUME_PERIOD = 20
VOLUME_MULTIPLIER = 1.10

MIN_MOMENTUM = 0.002
MIN_TREND_STRENGTH = 0.20
MAX_GREEN_CANDLE = 0.012

BUY_SCORE = 70
WATCH_SCORE = 62
IGNORE_SCORE = 55

RISK_PER_TRADE = 0.01
MAX_POSITION_PCT = 0.20
MAX_OPEN_POSITIONS = 5
DAILY_LOSS_LIMIT = 0.03
COOLDOWN_HOURS = 2

ATR_STOP_MULT = 1.8
REWARD_RISK = 3.0
BREAK_EVEN_AT = 1.0
TRAILING_STOP = True
TRAILING_AT_R = 1.5
TRAILING_ATR = 1.5

FEE_RATE = 0.001
SLIPPAGE_RATE = 0.0005

REPORT_INTERVAL_MINUTES = 30
LOG_SIGNALS = True
LOG_SKIPPED = False
LOG_POSITIONS = True

DB_FILE = "trading_bot_v4.db"

BASE_URL = "https://data-api.binance.vision"
REQUEST_TIMEOUT = 15
REQUEST_RETRIES = 3
RETRY_DELAY = 2

# Scanner protection: a symbol is not rescanned more often than this.
DATA_CACHE_SECONDS = 20
